services:
  postgres:
    image: postgres:16-alpine
    container_name: bigdata_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bigdata
      POSTGRES_PASSWORD: bigdata
      POSTGRES_DB: bigdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./01_create_mock_data.sql:/docker-entrypoint-initdb.d/01_create_mock_data.sql:ro
      - ./02_load_mock_data.sql:/docker-entrypoint-initdb.d/02_load_mock_data.sql:ro
      - ./03_dw_ddl.sql:/docker-entrypoint-initdb.d/03_dw_ddl.sql:ro
      - ./04_dw_dml.sql:/docker-entrypoint-initdb.d/04_dw_dml.sql:ro
      - "./исходные данные:/docker-entrypoint-initdb.d/data:ro"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
